spring.application.name=recipes-app
server.port=8091
server.servlet.context-path=/

logging.level.root=INFO
logging.level.com.recipes=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

server.error.include-message=always
server.error.include-stacktrace=on_param

